name: "Block Merge Commits"
description: "Prevent merging pull requests that contain commit messages prefixed with 'Merge Branch'"
author: "z3by"
branding:
  icon: "alert-triangle"
  color: "red"

inputs:
  repo-token:
    description: "Token for the repo. Can be passed in using {{ secrets.GITHUB_TOKEN }}"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
